In [1]:
import numpy as np

#### Array Manipulation and Slicing

###### Create a 5×5 matrix of random integers between 1–50.

In [2]:
array = np.random.randint(1, 51, size = (5,5))
array

array([[23, 39, 18, 12, 35],
       [45, 19,  4, 31, 35],
       [50, 33, 16, 24, 17],
       [48, 17, 37,  1, 43],
       [26,  6, 27, 10,  1]])

In [3]:
#Basic approach
def is_prime_basic(n):
    if n<= 1:
        return False
    for i in range(2,n):
        if n%i == 0:
            return False
    return True

for  i in range(array.shape[0]):
    for j in range(array.shape[1]):
        if is_prime_basic(array[i,j]):
            array[i,j]=0
array  

array([[ 0, 39, 18, 12, 35],
       [45,  0,  4,  0, 35],
       [50, 33, 16, 24,  0],
       [48,  0,  0,  1,  0],
       [26,  6, 27, 10,  1]])

In [4]:
#n to sqrt of n and using np.ndenumerate()
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(np.sqrt(n))+1):
        if n%i == 0:
           return False
    return True

for indx , val in np.ndenumerate(array):
    if is_prime(val):
        array[indx]=0
array


array([[ 0, 39, 18, 12, 35],
       [45,  0,  4,  0, 35],
       [50, 33, 16, 24,  0],
       [48,  0,  0,  1,  0],
       [26,  6, 27, 10,  1]])

In [5]:
#vectorized
def is_prime_vec(n):
    if n <= 1:
        return False
    return all(n % i != 0 for i in range(2, int(np.sqrt(n))+1))
prime_mask = np.vectorize(is_prime_vec)(array)
array[prime_mask] = 0

array

array([[ 0, 39, 18, 12, 35],
       [45,  0,  4,  0, 35],
       [50, 33, 16, 24,  0],
       [48,  0,  0,  1,  0],
       [26,  6, 27, 10,  1]])

###### Extract the diagonal elements and calculate their sum.

In [6]:
#Basic approach
sum=0
for i in range(array.shape[0]):
    sum += array[i,i]
sum

18

In [7]:
#using inbuilt functions
diag_ele = np.diag(array)
print(diag_ele)

sum_diag_ele  = np.sum(diag_ele)
print(sum_diag_ele)

#trace inbuilt function
print(np.trace(array))

[ 0  0 16  1  1]
18
18


#### Advanced Ufuncs

###### Create a 1D array of 8 numbers.

In [8]:
arr1 = np.arange(1,9) #always return 1D array
print(arr1)

[1 2 3 4 5 6 7 8]


###### Compute the cumulative product using np.multiply.accumulate().

In [9]:
print(np.multiply.accumulate(arr1))

[    1     2     6    24   120   720  5040 40320]


In [10]:
#inbult function
print(np.cumprod(arr1))

[    1     2     6    24   120   720  5040 40320]


###### Compute outer difference using np.subtract.outer()

In [11]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(np.subtract.outer(a1,a2))

[[-3 -4 -5]
 [-2 -3 -4]
 [-1 -2 -3]]


#### Real-World Data Simulation

###### Simulate a dataset with 10 samples and 4 features using random numbers.

In [12]:
#10 samples -> observation(rows)
#4 features -> variables(columns)
data  = np.random.rand(10,4)
print(data)

[[0.32667618 0.48377506 0.01536128 0.10516818]
 [0.76677377 0.49315179 0.74836152 0.05410961]
 [0.83413864 0.54257604 0.72300828 0.1907582 ]
 [0.38942064 0.11758264 0.43543615 0.71306803]
 [0.35411712 0.93346239 0.42952521 0.41164275]
 [0.22965409 0.32031079 0.89347236 0.29048432]
 [0.23162069 0.73102931 0.08610072 0.22104041]
 [0.44517347 0.02749838 0.12383338 0.52906935]
 [0.01089182 0.19802854 0.77785584 0.05471303]
 [0.69170534 0.84830259 0.85082986 0.44077038]]


In [14]:
#Alternative Random data 
# integer data set
data_int = np.random.randint(0,100,size=(10,4))
print(data_int)

[[31 45 15 23]
 [67 76 96 27]
 [64 39 18 70]
 [42 99  2 29]
 [82 65 19 42]
 [ 2 36 92 78]
 [ 0 56 36 40]
 [60 10 75 87]
 [89 49  6 88]
 [26 34 77 73]]


In [15]:
#Normally distributed data ml preferred
nor_data = np.random.randn(10,4)

In [16]:
print(nor_data)

[[ 1.08833552 -0.6011799   0.32458569  0.70071442]
 [ 1.97877565  0.38093656  0.40504882  0.77450886]
 [-2.27594375 -0.87634014  1.84628678 -0.4734977 ]
 [-0.12571307 -2.80057924 -1.67606729 -2.1173061 ]
 [ 2.07625973  1.10879453 -0.05735872 -1.70716868]
 [-0.18258849  1.39794631  1.37943422  1.57696504]
 [-0.49141102 -0.04899389  0.82554113  1.02134717]
 [ 0.32528536  1.2560183  -0.07457779  0.18472892]
 [-0.70345863  0.81112928 -0.55584866 -0.64131823]
 [-0.75840204  0.70622275  3.09212271  1.03484283]]


###### Standardize the dataset (mean=0, std=1) without using sklearn.

In [17]:
print("=====Actual Data======")
print(data)
mean = np.mean(data, axis = 0) #mean of each feature
std = np.std(data, axis = 0)  #std of each feature

stand_data = (data - mean) / std
print("=====Standardized Data=======")
print(stand_data)

=====Actual Data======
[[0.32667618 0.48377506 0.01536128 0.10516818]
 [0.76677377 0.49315179 0.74836152 0.05410961]
 [0.83413864 0.54257604 0.72300828 0.1907582 ]
 [0.38942064 0.11758264 0.43543615 0.71306803]
 [0.35411712 0.93346239 0.42952521 0.41164275]
 [0.22965409 0.32031079 0.89347236 0.29048432]
 [0.23162069 0.73102931 0.08610072 0.22104041]
 [0.44517347 0.02749838 0.12383338 0.52906935]
 [0.01089182 0.19802854 0.77785584 0.05471303]
 [0.69170534 0.84830259 0.85082986 0.44077038]]
=====Standardized Data=======
[[-0.40743894  0.0487623  -1.54169984 -0.94236076]
 [ 1.36196234  0.0809542   0.75044412 -1.18795596]
 [ 1.63280111  0.25063586  0.67116273 -0.53066701]
 [-0.15517639 -1.20843723 -0.2280958   1.98167864]
 [-0.29711333  1.59261381 -0.24657973  0.53180263]
 [-0.79751376 -0.51243774  1.20421608 -0.05097759]
 [-0.78960712  0.89762732 -1.3204926  -0.38500749]
 [ 0.06897643 -1.51771151 -1.20249988  1.09663252]
 [-1.67704197 -0.93225306  0.84267497 -1.18505347]
 [ 1.06015162  1.

In [18]:
#verification whether the data is standardized or not
print(np.mean(stand_data, axis = 0))   #mean = 0
print(np.std(stand_data, axis = 0))  #std = 1

[-2.22044605e-17 -2.22044605e-17 -6.66133815e-17  8.88178420e-17]
[1. 1. 1. 1.]


In [19]:
print(np.round(np.mean(stand_data, axis = 0)))

[-0. -0. -0.  0.]
