In [1]:
import numpy as np

#### Advanced Indexing and Slicing

###### Create a 5×5 NumPy array with random integers between 1 and 100.

In [3]:
array1 = np.random.randint(1,101,size = (5,5))
print(array1)

[[ 14  81   5  17   1]
 [ 64  20  89  73  78]
 [ 92  76  94  70   1]
 [ 63  80  75  17  35]
 [ 61 100  21  64  11]]


###### Replace all values greater than the column mean with -1.

In [4]:
col_mean = np.mean(array1,axis = 0)
print(col_mean)

[58.8 71.4 56.8 48.2 25.2]


In [6]:
mask = np.where(array1>col_mean)

In [7]:
array1[mask]=-1

In [8]:
array1

array([[14, -1,  5, 17,  1],
       [-1, 20, -1, -1, -1],
       [-1, -1, -1, -1,  1],
       [-1, -1, -1, 17, -1],
       [-1, -1, 21, -1, 11]])

#### Linear Algebra (Core DS Skill)

###### Create a 4×4 matrix.

In [9]:
arr = np.random.randint(1,51,size = (4,4))
arr

array([[39, 43, 13, 48],
       [21, 43, 16,  2],
       [24, 35, 28, 39],
       [13, 41,  8,  3]])

###### Compute: Transpose , Determinant , Rank

In [10]:
np.transpose(arr)

array([[39, 21, 24, 13],
       [43, 43, 35, 41],
       [13, 16, 28,  8],
       [48,  2, 39,  3]])

In [11]:
np.linalg.det(arr)

366312.99999999977

In [12]:
np.linalg.matrix_rank(arr)

4

#### Real-World Normalization Task

###### Simulate a dataset with 12 samples and 4 features.

In [14]:
data  = np.random.randint(1,100,size = (12,4))
data

array([[80, 42, 66, 13],
       [49,  3, 57, 84],
       [56, 66, 97, 52],
       [99,  9, 48, 48],
       [ 8, 63, 93, 63],
       [15, 75, 28, 13],
       [99, 68, 57, 77],
       [15, 93, 25, 36],
       [55,  9, 14, 35],
       [36, 87, 63, 27],
       [50, 30, 60, 84],
       [38, 30, 71,  6]])

###### Perform : Min- Max normalization , z-score normalization

In [15]:
min_data = np.min(data , axis = 0)
max_data = np.max(data , axis = 0)

nor = (data - min_data) / (max_data - min_data)
nor

array([[0.79120879, 0.43333333, 0.62650602, 0.08974359],
       [0.45054945, 0.        , 0.51807229, 1.        ],
       [0.52747253, 0.7       , 1.        , 0.58974359],
       [1.        , 0.06666667, 0.40963855, 0.53846154],
       [0.        , 0.66666667, 0.95180723, 0.73076923],
       [0.07692308, 0.8       , 0.1686747 , 0.08974359],
       [1.        , 0.72222222, 0.51807229, 0.91025641],
       [0.07692308, 1.        , 0.13253012, 0.38461538],
       [0.51648352, 0.06666667, 0.        , 0.37179487],
       [0.30769231, 0.93333333, 0.59036145, 0.26923077],
       [0.46153846, 0.3       , 0.55421687, 1.        ],
       [0.32967033, 0.3       , 0.68674699, 0.        ]])

In [16]:
mean_data = np.mean(data , axis = 0)
std_data = np.std(data , axis = 0)

nor_z = (data - mean_data )/ std_data
nor_z

array([[ 1.02309065, -0.19564426,  0.38958338, -1.19456688],
       [-0.03410302, -1.48524304,  0.0172382 ,  1.46975506],
       [ 0.20461813,  0.59795499,  1.67210565,  0.2689339 ],
       [ 1.67104806, -1.28684323, -0.35510697,  0.11883126],
       [-1.43232691,  0.49875508,  1.5066189 ,  0.68171618],
       [-1.19360576,  0.89555471, -1.18254069, -1.19456688],
       [ 1.67104806,  0.66408826,  0.0172382 ,  1.20707543],
       [-1.19360576,  1.49075415, -1.30665575, -0.33147667],
       [ 0.17051511, -1.28684323, -1.7617443 , -0.36900233],
       [-0.4774423 ,  1.29235434,  0.26546832, -0.66920762],
       [ 0.        , -0.59244389,  0.14135326,  1.46975506],
       [-0.40923626, -0.59244389,  0.59644181, -1.45724651]])